stars-at-daybreak/morningStarRecipe

src/App.tsx
src/pages/home/Home.tsx
src/pages/mypage/Mypage.tsx
src/pages/mypage/ProfileEditForm.tsx
src/services/supabaseUsers.ts
src/types/users.ts

feature: 회원정보 수정 api 연결 작업

---

src/components/RecipeForm.tsx
src/hooks/useSearch.tsx
src/pages/recipes/Recipes.tsx
src/services/supabasePosts.ts
src/types/search.types.ts

- 데이터 목록 조회 (커스텀 useSearch 훅 사용)
- 레시피 목록 조회 필터 (커스텀 useSearch 훅 사용)

feature: 레시피 목록 조회

---

src/App.tsx
src/components/PostComments.tsx
src/components/RecipeDetail.tsx
src/components/RecipeForm.tsx
src/pages/recipes/Recipes.tsx
src/services/supabaseComments.ts
src/services/supabasePosts.ts
src/types/myPosts.types.ts

- 댓글 CRUD 기능 작업
- 레시피 생성, 수정 로직 변경 및 삭제 기능 추가

댓글 CRUD 기능 작업

---

src/components/PostComments.tsx
src/services/supabaseComments.ts
src/types/comments.type.ts

- 댓글 조회시 닉네임 조회
- 댓글 삭제시 데이터 삭제가 아닌 삭제 플래그 업데이트 방식으로 수정

댓글 조회 및 삭제 로직 수정

---

src/hooks/useSearch.tsx
src/pages/search/Search.tsx
src/providers/AuthProvider.tsx

검색 최적화 작업
- [ ✅] 리팩토링
- [✅ ] 로컬에서 정상 동작 확인.
- [✅ ] 코드가 컨벤션을 따르고 있습니다.
- [ ✅] 불필요한 console.log를 제거했습니다.

refactor : 최적화 작업

---

src/components/input/inputText.module.css
src/pages/signup/signup.module.css

feature: 회원가입

---

src/components/PasswordFind.tsx
src/components/button/EmailAuthButton.tsx
src/components/button/KakaoLoginButton.tsx
src/pages/signup/SignUp.tsx

refactor: 버튼 컴포넌트 위치 이동

---

src/assets/minus_icon.svg
src/assets/plus_icon.svg
src/assets/topBtn_icon.svg
src/components/FloatingButtons/FloatingButtons.module.css
src/components/FloatingButtons/FloatingButtons.tsx
src/pages/Layout/Layout.module.css
src/pages/Layout/Layout.tsx
src/styles/common.css
src/types/colorSet.ts

- 폰트사이즈 컨트롤 기능 추가
- 탑버튼 기능 추가
- 컬러셋 gray-700(#555555) 추가
- y스크롤 숨김처리

feat/ 플로팅 버튼 작업

---

src/components/LevelBadge/LevelBadge.module.css
src/components/LevelBadge/LevelBadge.tsx

Feature/뱃지 컴포넌트 작업

---

src/components/postItem/PostItem.module.css

refactor/ title 행간 수정

---

src/components/postItem/PostItem.module.css

refactor: 나눔게시물 margin값 수정

---

src/components/modal/Modal.tsx
src/components/modal/ModalContext.ts
src/components/modal/getModalContent.tsx

feat/ 모달 타입추가

---

src/assets/comments_icon.svg
src/components/ShareDetail.tsx
src/components/post/PostCommentInput.tsx
src/components/post/PostComments.tsx
src/components/post/postCommentInput.module.css
src/components/post/postComments.module.css
src/pages/recipes/RecipeDetail.tsx
src/pages/recipes/recipeDetail.module.css
src/types/comments.type.ts

feature: 레시피 댓글 컴포넌트 작업(미완료)

---

src/components/modal/Modal.tsx
src/components/modal/ModalContext.ts
src/components/modal/ModalProvider.tsx
src/components/modal/getModalContent.tsx
src/components/post/PostCommentInput.tsx
src/components/post/PostComments.tsx
src/components/post/postComments.module.css
src/pages/recipes/RecipeDetail.tsx
src/pages/recipes/RecipeForm.tsx
src/pages/recipes/recipeDetail.module.css
src/utils/utils.ts

- 레시피부분 alert을 모달로 변경
- 모달 type DELETE 콜백함수 받도록 변경
- 남은 댓글 작업 완료

feature: 레시피 댓글 작업 완료

---

src/components/modal/emailAuthModal.module.css
src/pages/mypage/MyPostList.tsx

- 이메일인증모달창 CSS수정
- 레시피 개시물 이동시 렌더링 오류 수정

refactor/이메일 인증모달창 CSS 수정 및 레시피 게시물 이동시 렌더링 오류 수정

---

src/pages/recipes/RecipeDetail.tsx
src/pages/recipes/RecipeForm.tsx
src/pages/recipes/recipeForm.module.css

- 등록, 수정 기능 연결 (나눔 등록, 수정과 CSS 동일하게 맞춤)
- 검증로직 추가 예정

feature: 레시피 등록, 수정 작업중

---

src/components/header/Header.tsx
src/components/modal/getModalContent.tsx
src/pages/share/ShareForm.tsx

- 글 작성중 뒤로가기 클릭 시  확인 모달
- 모달 취소 확인 위치 변경 
- 기본값 서울 => '' 변겅
- [✅] 새로운 기능 추가
- [✅] 버그 수정
- [✅] 리팩토링
- [✅] 로컬에서 정상 동작 확인.
- [✅] 코드가 컨벤션을 따르고 있습니다.
- [✅] 불필요한 console.log를 제거했습니다.
- [✅] 반응형 디자인을 확인했습니다.

feat : 글 작성중 뒤로가기 클릭 시  확인 모달

---

src/components/modal/EmailAuthModal.tsx
src/components/modal/emailAuthModal.module.css
src/components/post/postComments.module.css
src/pages/recipes/RecipeDetail.tsx
src/pages/recipes/RecipeForm.tsx
src/pages/recipes/recipeForm.module.css

- 에디터에 저장된 JSON값을 HTML로 변환하는 컴포넌트 추가
- 회원가입 이메일 인증 모달 css 수정

feature: 레시피 상세화면 데이터 노출되도록 추가

---

src/pages/recipes/Recipes.tsx

- 프롭스 제거 후 const query = new URLSearchParams(window.location.search).get('query') || ''; 추가

refactor: 사용안하는 props 제거

---

src/components/LexicalEditor/LexicalEditor.css
src/components/LexicalEditor/LexicalEditor.tsx
src/components/LexicalEditor/LexicalRenderer.tsx
src/components/LexicalEditor/commands/YouTubeCommands.ts
src/components/LexicalEditor/components/LinkPreview.module.css
src/components/LexicalEditor/components/LinkPreview.tsx
src/components/LexicalEditor/components/YouTubeComponent.tsx
src/components/LexicalEditor/nodes/YouTubeNode.tsx
src/components/LexicalEditor/plugins/ToolbarPlugin.tsx
src/components/LexicalEditor/plugins/YouTubePlugin.tsx
src/components/LexicalEditor/utils/youtubeUtils.ts
src/pages/recipes/RecipeForm.tsx
src/utils/lexicalUtils.ts
src/utils/linkPreview.ts

- 오토링크 플러그인 적용
- 커스텀 유튜브 플러그인 적용

feature: lexical editor의 오토링크 플러그인, 커스텀 유튜브 플러그인 적용

---

src/components/postItem/PostItem.module.css

- PostItem 컴포넌트 word-break: break-word 추가

feature: PostItem 컴포넌트 word-break: break-word 추가

---

src/components/LexicalEditor/LexicalRenderer.module.css
src/components/postItem/PostItem.module.css
src/pages/recipes/RecipeDetail.tsx
src/pages/recipes/recipeDetail.module.css
src/pages/share/ShareDetail.module.css

feature: 게시물 상세 css 수정

---

src/App.tsx

- 라우터에서 인증된 사용자가 아니면 진입할 수 없는 페이지 설정

feature: 라우터에서 인증된 사용자가 아니면 진입할 수 없는 페이지 설정

---

src/components/postItem/PostItem.module.css
src/components/postItem/PostItem.tsx

refactor: 나눔취소 상태 텍스트 및 컬러 변경

---

src/pages/home/Home.tsx

메인 레시피 , 최근 게시물 위치 변경
- [✅ ] 리팩토링
- [✅ ] 로컬에서 정상 동작 확인.
- [ ✅] 코드가 컨벤션을 따르고 있습니다.
- [✅ ] 불필요한 console.log를 제거했습니다.
- [✅ ] 반응형 디자인을 확인했습니다.

refactor : 메인 레시피 , 최근 게시물 위치 변경
